### ISSUE TITLE
Working in Firefox?

### ISSUE THREAD

**Issue by bryanmcgrane** [chrisguttandin/extendable-media-recorder-wav-encoder#393]
I've been using this wav encoder with much success in my angular application, but Firefox gives me the following error:

```
TypeError: this._encoderPort is null
```
![image](https://user-images.githubusercontent.com/3849234/117343565-a64c2180-ae61-11eb-8540-5fc541c5f372.png)

**Comment by chrisguttandin** [comment]
I think the issue should be fixed with the patch referenced above. But it's of course only a guess without having a test case to reproduce the issue.

Could you please test again with v6.1.63 of extendable-media-recorder?

**Comment by bryanmcgrane** [comment]
Confirmed. The error is not thrown anymore!

**Comment by chrisguttandin** [comment]
Thanks for letting me know. I'm happy to hear that.
