### ISSUE TITLE
Firefox/React: Video cannot be recorded with audio/wav as it is an audio type

### ISSUE THREAD

**Issue by yuvalkry** [chrisguttandin/extendable-media-recorder-wav-encoder#395]
Hello,

 I am trying to create an audio recorder using the extendable-media-recorder and the wav encoder plugin,
 the code runs under react (if that matters).

```
  import { MediaRecorder, register } from 'extendable-media-recorder';
  import { connect } from 'extendable-media-recorder-wav-encoder';

  connect().then(register).catch((err) => console.log("Could not connect to the wav encoder.", err))

  navigator.mediaDevices.getUserMedia({ audio: true, video: false })
    .then((stream) =>
     {mediaRecorder = new MediaRecorder(stream, { mimeType: 'audio/wav' });
      mediaRecorder.ondataavailable = handleDataAvailable;})
    .catch((err) => console.error("Uh oh... unable to get stream...", err));
```

  On chrome and edge (latest versions) it runs well.
  On Firefox, I do not get the wav encoder error but I get the error from the MediaRecorder constructor:
   Uh oh... unable to get stream... DOMException: MediaRecorder constructor: Video cannot be recorded with audio/wav as it is an audio type

 The script runs under a react app and created on an npm environment, the relevant pacages are:
 $npm ls | grep record
├── extendable-media-recorder-wav-encoder@7.0.56
├── extendable-media-recorder@6.3.4
├── recorder-audio-worklet-processor@4.1.4
├── recorder-audio-worklet@5.0.76
├── recorder-js@1.0.7

   Many thanks,
          Yuval

**Comment by chrisguttandin** [comment]
Hi Yuval,

it looks like you're using the `MediaRecorder` before the codec has been loaded. `connect().then(register)` needs to be done before you can create a `MediaRecorder` with the `'audio/wav'` `mimeType`. Before the custom codec is available `extendable-media-recorder` will use the native `MediaRecorder` as a fallback which throws this cryptic error in Firefox.

**Comment by yuvalkry** [comment]
Thanks Chris,

I followed the example in [https://stackblitz.com/edit/js-acfyyc?file=index.js](https://stackblitz.com/edit/js-acfyyc?file=index.js) and did not get the message.

     Yuval
