### ISSUE TITLE
Setting the sample rate

### ISSUE THREAD

**Issue by yuvalkry** [chrisguttandin/extendable-media-recorder-wav-encoder#396]
Chris, thank you for that recorder, which makes it possible to use the modern APIs.

Are you planning to implement possibility to set the sample rate of the wav encoding? Perhaps through ``AudioContext`` ?

  Yuval

**Comment by chrisguttandin** [comment]
Hi @yuvalkry,

the ` record()` function of this package accepts a `sampleRate` param which gets used when encoding the audio.

But I guess you rather asked for support for setting the sampleRate when using this package with extendable-media-recorder, right?

I just made a few adjustments to extendable-media-recorder which make sure the sampleRate of the passed in `MediaStream` gets now used to encode the audio with the same sampleRate.

For browsers which do not expose the sampleRate of MediaStream you can patch it as follows if the sampleRate is for example 44.1kHz.

```js
const [firstAudioTrack] = mediaStream.getAudioTracks();
const channelCount = 1;

if (firstAudioTrack.getSettings().sampleRate === undefined) {
    firstAudioTrack.getSettings = ((getSettings) => () => ({
        sampleRate: 44100,
        ...getSettings.call(firstAudioTrack)
    }))(firstAudioTrack.getSettings);
}
```

It works similar to specifying the channelCount. chrisguttandin/extendable-media-recorder#644
